### ISSUE TITLE
Compilation fails on clean checkout

### ISSUE THREAD

**Issue by Eddi-z** [OpenTTD/grfcodec#11] opened 2021-01-15 17:46 UTC
```
grfcodec> LC_ALL=C make
Makefile:55: *** invalid syntax in conditional.  Stop.
```

Version: master (5a00dc3f0393c55cb35b29f56ba8143ffa606214)
OS: Linux/OpenSUSE

**Comment by LordAro** [comment] 2021-01-15 17:52
Cannot reproduce.

https://github.com/OpenTTD/grfcodec/blob/5a00dc3f0393c55cb35b29f56ba8143ffa606214/Makefile#L55

That line isn't the simplest thing in the world, but there's nothing in there that i'd expect to be invalid syntax-wise

Can you try the following above that line (might need to comment out that block entirely) to see what's causing it?
```
$(info $(shell echo "#include <stdio.h>"))
$(info $(shell echo "#include <stdio.h>" | $(CXX) -E -x c++ -))
$(info $(shell echo "#include <stdio.h>" | $(CXX) -E -x c++ - | grep fmemopen))
$(info $(shell echo "#include <stdio.h>" | $(CXX) -E -x c++ - | grep fmemopen | wc -l))
$(info $(shell echo "#include <stdio.h>" | $(CXX) -E -x c++ - | grep fmemopen | wc -l | sed "s/ *//"))
```

**Comment by Eddi-z** [comment] 2021-01-15 18:01
new output with those lines

```
grfcodec> LC_ALL=C make
#include <stdio.h>
# 1 "<stdin>" # 1 "<built-in>" # 1 "<command-line>" # 1 "/usr/include/stdc-predef.h" 1 3 4 # 1 "<command-line>" 2 # 1 "<stdin>" # 1 "/usr/include/stdio.h" 1 3 4 # 27 "/usr/include/stdio.h" 3 4 # 1 "/usr/include/bits/libc-header-start.h" 1 3 4 # 33 "/usr/include/bits/libc-header-start.h" 3 4 # 1 "/usr/include/features.h" 1 3 4 # 423 "/usr/include/features.h" 3 4 # 1 "/usr/include/sys/cdefs.h" 1 3 4 # 419 "/usr/include/sys/cdefs.h" 3 4 # 1 "/usr/include/bits/wordsize.h" 1 3 4 # 420 "/usr/include/sys/cdefs.h" 2 3 4 # 1 "/usr/include/bits/long-double.h" 1 3 4 # 421 "/usr/include/sys/cdefs.h" 2 3 4 # 424 "/usr/include/features.h" 2 3 4 # 447 "/usr/include/features.h" 3 4 # 1 "/usr/include/gnu/stubs.h" 1 3 4 # 10 "/usr/include/gnu/stubs.h" 3 4 # 1 "/usr/include/gnu/stubs-64.h" 1 3 4 # 11 "/usr/include/gnu/stubs.h" 2 3 4 # 448 "/usr/include/features.h" 2 3 4 # 34 "/usr/include/bits/libc-header-start.h" 2 3 4 # 28 "/usr/include/stdio.h" 2 3 4   # 29 "/usr/include/stdio.h" 3 4 extern "C" {    # 1 "/usr/lib64/gcc/x86_64-suse-linux/7/include/stddef.h" 1 3 4 # 216 "/usr/lib64/gcc/x86_64-suse-linux/7/include/stddef.h" 3 4 typedef long unsigned int size_t; # 34 "/usr/include/stdio.h" 2 3 4  # 1 "/usr/include/bits/types.h" 1 3 4 # 27 "/usr/include/bits/types.h" 3 4 # 1 "/usr/include/bits/wordsize.h" 1 3 4 # 28 "/usr/include/bits/types.h" 2 3 4   typedef unsigned char __u_char; typedef unsigned short int __u_short; typedef unsigned int __u_int; typedef unsigned long int __u_long;   typedef signed char __int8_t; typedef unsigned char __uint8_t; typedef signed short int __int16_t; typedef unsigned short int __uint16_t; typedef signed int __int32_t; typedef unsigned int __uint32_t;  typedef signed long int __int64_t; typedef unsigned long int __uint64_t;        typedef long int __quad_t; typedef unsigned long int __u_quad_t;        typedef long int __intmax_t; typedef unsigned long int __uintmax_t; # 130 "/usr/include/bits/types.h" 3 4 # 1 "/usr/include/bits/typesizes.h" 1 3 4 # 131 "/usr/include/bits/types.h" 2 3 4   typedef unsigned long int __dev_t; typedef unsigned int __uid_t; typedef unsigned int __gid_t; typedef unsigned long int __ino_t; typedef unsigned long int __ino64_t; typedef unsigned int __mode_t; typedef unsigned long int __nlink_t; typedef long int __off_t; typedef long int __off64_t; typedef int __pid_t; typedef struct { int __val[2]; } __fsid_t; typedef long int __clock_t; typedef unsigned long int __rlim_t; typedef unsigned long int __rlim64_t; typedef unsigned int __id_t; typedef long int __time_t; typedef unsigned int __useconds_t; typedef long int __suseconds_t;  typedef int __daddr_t; typedef int __key_t;   typedef int __clockid_t;   typedef void * __timer_t;   typedef long int __blksize_t;     typedef long int __blkcnt_t; typedef long int __blkcnt64_t;   typedef unsigned long int __fsblkcnt_t; typedef unsigned long int __fsblkcnt64_t;   typedef unsigned long int __fsfilcnt_t; typedef unsigned long int __fsfilcnt64_t;   typedef long int __fsword_t;  typedef long int __ssize_t;   typedef long int __syscall_slong_t;  typedef unsigned long int __syscall_ulong_t;    typedef __off64_t __loff_t; typedef __quad_t *__qaddr_t; typedef char *__caddr_t;   typedef long int __intptr_t;   typedef unsigned int __socklen_t;     typedef int __sig_atomic_t; # 36 "/usr/include/stdio.h" 2 3 4 # 1 "/usr/include/bits/types/__FILE.h" 1 3 4    struct _IO_FILE; typedef struct _IO_FILE __FILE; # 37 "/usr/include/stdio.h" 2 3 4 # 1 "/usr/include/bits/types/FILE.h" 1 3 4    struct _IO_FILE;   typedef struct _IO_FILE FILE; # 38 "/usr/include/stdio.h" 2 3 4    # 1 "/usr/include/libio.h" 1 3 4 # 31 "/usr/include/libio.h" 3 4 # 1 "/usr/include/_G_config.h" 1 3 4 # 15 "/usr/include/_G_config.h" 3 4 # 1 "/usr/lib64/gcc/x86_64-suse-linux/7/include/stddef.h" 1 3 4 # 16 "/usr/include/_G_config.h" 2 3 4  # 1 "/usr/include/bits/types/__mbstate_t.h" 1 3 4 # 13 "/usr/include/bits/types/__mbstate_t.h" 3 4 typedef struct {   int __count;   union   {     unsigned int __wch;     char __wchb[4];   } __value; } __mbstate_t; # 18 "/usr/include/_G_config.h" 2 3 4     typedef struct {   __off_t __pos;   __mbstate_t __state; } _G_fpos_t; typedef struct {   __off64_t __pos;   __mbstate_t __state; } _G_fpos64_t; # 32 "/usr/include/libio.h" 2 3 4 # 49 "/usr/include/libio.h" 3 4 # 1 "/usr/lib64/gcc/x86_64-suse-linux/7/include/stdarg.h" 1 3 4 # 40 "/usr/lib64/gcc/x86_64-suse-linux/7/include/stdarg.h" 3 4 typedef __builtin_va_list __gnuc_va_list; # 50 "/usr/include/libio.h" 2 3 4 # 145 "/usr/include/libio.h" 3 4 struct _IO_jump_t; struct _IO_FILE;     typedef void _IO_lock_t;      struct _IO_marker {   struct _IO_marker *_next;   struct _IO_FILE *_sbuf;      int _pos; # 173 "/usr/include/libio.h" 3 4 };   enum __codecvt_result {   __codecvt_ok,   __codecvt_partial,   __codecvt_error,   __codecvt_noconv }; # 241 "/usr/include/libio.h" 3 4 struct _IO_FILE {   int _flags;       char* _IO_read_ptr;   char* _IO_read_end;   char* _IO_read_base;   char* _IO_write_base;   char* _IO_write_ptr;   char* _IO_write_end;   char* _IO_buf_base;   char* _IO_buf_end;    char *_IO_save_base;   char *_IO_backup_base;   char *_IO_save_end;    struct _IO_marker *_markers;    struct _IO_FILE *_chain;    int _fileno;      int _flags2;    __off_t _old_offset;      unsigned short _cur_column;   signed char _vtable_offset;   char _shortbuf[1];      _IO_lock_t *_lock; # 289 "/usr/include/libio.h" 3 4   __off64_t _offset;          void *__pad1;   void *__pad2;   void *__pad3;   void *__pad4;    size_t __pad5;   int _mode;    char _unused2[15 * sizeof (int) - 4 * sizeof (void *) - sizeof (size_t)];  };      struct _IO_FILE_plus;  extern struct _IO_FILE_plus _IO_2_1_stdin_; extern struct _IO_FILE_plus _IO_2_1_stdout_; extern struct _IO_FILE_plus _IO_2_1_stderr_; # 333 "/usr/include/libio.h" 3 4 typedef __ssize_t __io_read_fn (void *__cookie, char *__buf, size_t __nbytes);        typedef __ssize_t __io_write_fn (void *__cookie, const char *__buf,      size_t __n);        typedef int __io_seek_fn (void *__cookie, __off64_t *__pos, int __w);   typedef int __io_close_fn (void *__cookie);     typedef __io_read_fn cookie_read_function_t; typedef __io_write_fn cookie_write_function_t; typedef __io_seek_fn cookie_seek_function_t; typedef __io_close_fn cookie_close_function_t;   typedef struct {   __io_read_fn *read;   __io_write_fn *write;   __io_seek_fn *seek;   __io_close_fn *close; } _IO_cookie_io_functions_t; typedef _IO_cookie_io_functions_t cookie_io_functions_t;  struct _IO_cookie_file;   extern void _IO_cookie_init (struct _IO_cookie_file *__cfile, int __read_write,         void *__cookie, _IO_cookie_io_functions_t __fns);     extern "C" {   extern int __underflow (_IO_FILE *); extern int __uflow (_IO_FILE *); extern int __overflow (_IO_FILE *, int); # 429 "/usr/include/libio.h" 3 4 extern int _IO_getc (_IO_FILE *__fp); extern int _IO_putc (int __c, _IO_FILE *__fp); extern int _IO_feof (_IO_FILE *__fp) throw (); extern int _IO_ferror (_IO_FILE *__fp) throw ();  extern int _IO_peekc_locked (_IO_FILE *__fp);      extern void _IO_flockfile (_IO_FILE *) throw (); extern void _IO_funlockfile (_IO_FILE *) throw (); extern int _IO_ftrylockfile (_IO_FILE *) throw (); # 458 "/usr/include/libio.h" 3 4 extern int _IO_vfscanf (_IO_FILE * __restrict, const char * __restrict,    __gnuc_va_list, int *__restrict); extern int _IO_vfprintf (_IO_FILE *__restrict, const char *__restrict,     __gnuc_va_list); extern __ssize_t _IO_padn (_IO_FILE *, int, __ssize_t); extern size_t _IO_sgetn (_IO_FILE *, void *, size_t);  extern __off64_t _IO_seekoff (_IO_FILE *, __off64_t, int, int); extern __off64_t _IO_seekpos (_IO_FILE *, __off64_t, int);  extern void _IO_free_backup_area (_IO_FILE *) throw (); # 520 "/usr/include/libio.h" 3 4 } # 42 "/usr/include/stdio.h" 2 3 4     typedef __gnuc_va_list va_list; # 57 "/usr/include/stdio.h" 3 4 typedef __off_t off_t;       typedef __off64_t off64_t;       typedef __ssize_t ssize_t;       typedef _G_fpos_t fpos_t;     typedef _G_fpos64_t fpos64_t; # 131 "/usr/include/stdio.h" 3 4 # 1 "/usr/include/bits/stdio_lim.h" 1 3 4 # 132 "/usr/include/stdio.h" 2 3 4    extern struct _IO_FILE *stdin; extern struct _IO_FILE *stdout; extern struct _IO_FILE *stderr;       extern int remove (const char *__filename) throw ();  extern int rename (const char *__old, const char *__new) throw ();    extern int renameat (int __oldfd, const char *__old, int __newfd,        const char *__new) throw ();        extern FILE *tmpfile (void) ; # 169 "/usr/include/stdio.h" 3 4 extern FILE *tmpfile64 (void) ;    extern char *tmpnam (char *__s) throw () ;     extern char *tmpnam_r (char *__s) throw () ; # 190 "/usr/include/stdio.h" 3 4 extern char *tempnam (const char *__dir, const char *__pfx)      throw () __attribute__ ((__malloc__)) ;        extern int fclose (FILE *__stream);     extern int fflush (FILE *__stream); # 213 "/usr/include/stdio.h" 3 4 extern int fflush_unlocked (FILE *__stream); # 223 "/usr/include/stdio.h" 3 4 extern int fcloseall (void); # 232 "/usr/include/stdio.h" 3 4 extern FILE *fopen (const char *__restrict __filename,       const char *__restrict __modes) ;     extern FILE *freopen (const char *__restrict __filename,         const char *__restrict __modes,         FILE *__restrict __stream) ; # 256 "/usr/include/stdio.h" 3 4 extern FILE *fopen64 (const char *__restrict __filename,         const char *__restrict __modes) ; extern FILE *freopen64 (const char *__restrict __filename,    const char *__restrict __modes,    FILE *__restrict __stream) ;     extern FILE *fdopen (int __fd, const char *__modes) throw () ;      extern FILE *fopencookie (void *__restrict __magic_cookie,      const char *__restrict __modes,      _IO_cookie_io_functions_t __io_funcs) throw () ;     extern FILE *fmemopen (void *__s, size_t __len, const char *__modes)   throw () ;     extern FILE *open_memstream (char **__bufloc, size_t *__sizeloc) throw () ;      extern void setbuf (FILE *__restrict __stream, char *__restrict __buf) throw ();    extern int setvbuf (FILE *__restrict __stream, char *__restrict __buf,       int __modes, size_t __n) throw ();     extern void setbuffer (FILE *__restrict __stream, char *__restrict __buf,          size_t __size) throw ();   extern void setlinebuf (FILE *__stream) throw ();        extern int fprintf (FILE *__restrict __stream,       const char *__restrict __format, ...);     extern int printf (const char *__restrict __format, ...);  extern int sprintf (char *__restrict __s,       const char *__restrict __format, ...) throw ();      extern int vfprintf (FILE *__restrict __s, const char *__restrict __format,        __gnuc_va_list __arg);     extern int vprintf (const char *__restrict __format, __gnuc_va_list __arg);  extern int vsprintf (char *__restrict __s, const char *__restrict __format,        __gnuc_va_list __arg) throw ();    extern int snprintf (char *__restrict __s, size_t __maxlen,        const char *__restrict __format, ...)      throw () __attribute__ ((__format__ (__printf__, 3, 4)));  extern int vsnprintf (char *__restrict __s, size_t __maxlen,         const char *__restrict __format, __gnuc_va_list __arg)      throw () __attribute__ ((__format__ (__printf__, 3, 0)));      extern int vasprintf (char **__restrict __ptr, const char *__restrict __f,         __gnuc_va_list __arg)      throw () __attribute__ ((__format__ (__printf__, 2, 0))) ; extern int __asprintf (char **__restrict __ptr,          const char *__restrict __fmt, ...)      throw () __attribute__ ((__format__ (__printf__, 2, 3))) ; extern int asprintf (char **__restrict __ptr,        const char *__restrict __fmt, ...)      throw () __attribute__ ((__format__ (__printf__, 2, 3))) ;     extern int vdprintf (int __fd, const char *__restrict __fmt,        __gnuc_va_list __arg)      __attribute__ ((__format__ (__printf__, 2, 0))); extern int dprintf (int __fd, const char *__restrict __fmt, ...)      __attribute__ ((__format__ (__printf__, 2, 3)));        extern int fscanf (FILE *__restrict __stream,      const char *__restrict __format, ...) ;     extern int scanf (const char *__restrict __format, ...) ;  extern int sscanf (const char *__restrict __s,      const char *__restrict __format, ...) throw (); # 420 "/usr/include/stdio.h" 3 4 extern int vfscanf (FILE *__restrict __s, const char *__restrict __format,       __gnuc_va_list __arg)      __attribute__ ((__format__ (__scanf__, 2, 0))) ;      extern int vscanf (const char *__restrict __format, __gnuc_va_list __arg)      __attribute__ ((__format__ (__scanf__, 1, 0))) ;   extern int vsscanf (const char *__restrict __s,       const char *__restrict __format, __gnuc_va_list __arg)      throw () __attribute__ ((__format__ (__scanf__, 2, 0))); # 477 "/usr/include/stdio.h" 3 4 extern int fgetc (FILE *__stream); extern int getc (FILE *__stream);      extern int getchar (void); # 495 "/usr/include/stdio.h" 3 4 extern int getc_unlocked (FILE *__stream); extern int getchar_unlocked (void); # 506 "/usr/include/stdio.h" 3 4 extern int fgetc_unlocked (FILE *__stream); # 517 "/usr/include/stdio.h" 3 4 extern int fputc (int __c, FILE *__stream); extern int putc (int __c, FILE *__stream);      extern int putchar (int __c); # 537 "/usr/include/stdio.h" 3 4 extern int fputc_unlocked (int __c, FILE *__stream);        extern int putc_unlocked (int __c, FILE *__stream); extern int putchar_unlocked (int __c);       extern int getw (FILE *__stream);   extern int putw (int __w, FILE *__stream);        extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)      ; # 587 "/usr/include/stdio.h" 3 4 extern char *fgets_unlocked (char *__restrict __s, int __n,         FILE *__restrict __stream) ; # 603 "/usr/include/stdio.h" 3 4 extern __ssize_t __getdelim (char **__restrict __lineptr,           size_t *__restrict __n, int __delimiter,           FILE *__restrict __stream) ; extern __ssize_t getdelim (char **__restrict __lineptr,         size_t *__restrict __n, int __delimiter,         FILE *__restrict __stream) ;        extern __ssize_t getline (char **__restrict __lineptr,        size_t *__restrict __n,        FILE *__restrict __stream) ;        extern int fputs (const char *__restrict __s, FILE *__restrict __stream);      extern int puts (const char *__s);       extern int ungetc (int __c, FILE *__stream);       extern size_t fread (void *__restrict __ptr, size_t __size,        size_t __n, FILE *__restrict __stream) ;     extern size_t fwrite (const void *__restrict __ptr, size_t __size,         size_t __n, FILE *__restrict __s); # 662 "/usr/include/stdio.h" 3 4 extern int fputs_unlocked (const char *__restrict __s,       FILE *__restrict __stream); # 673 "/usr/include/stdio.h" 3 4 extern size_t fread_unlocked (void *__restrict __ptr, size_t __size,          size_t __n, FILE *__restrict __stream) ; extern size_t fwrite_unlocked (const void *__restrict __ptr, size_t __size,           size_t __n, FILE *__restrict __stream);        extern int fseek (FILE *__stream, long int __off, int __whence);     extern long int ftell (FILE *__stream) ;     extern void rewind (FILE *__stream); # 707 "/usr/include/stdio.h" 3 4 extern int fseeko (FILE *__stream, __off_t __off, int __whence);     extern __off_t ftello (FILE *__stream) ; # 731 "/usr/include/stdio.h" 3 4 extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);     extern int fsetpos (FILE *__stream, const fpos_t *__pos); # 750 "/usr/include/stdio.h" 3 4 extern int fseeko64 (FILE *__stream, __off64_t __off, int __whence); extern __off64_t ftello64 (FILE *__stream) ; extern int fgetpos64 (FILE *__restrict __stream, fpos64_t *__restrict __pos); extern int fsetpos64 (FILE *__stream, const fpos64_t *__pos);    extern void clearerr (FILE *__stream) throw ();  extern int feof (FILE *__stream) throw () ;  extern int ferror (FILE *__stream) throw () ;    extern void clearerr_unlocked (FILE *__stream) throw (); extern int feof_unlocked (FILE *__stream) throw () ; extern int ferror_unlocked (FILE *__stream) throw () ;        extern void perror (const char *__s);      # 1 "/usr/include/bits/sys_errlist.h" 1 3 4 # 26 "/usr/include/bits/sys_errlist.h" 3 4 extern int sys_nerr; extern const char *const sys_errlist[];   extern int _sys_nerr; extern const char *const _sys_errlist[]; # 782 "/usr/include/stdio.h" 2 3 4     extern int fileno (FILE *__stream) throw () ;     extern int fileno_unlocked (FILE *__stream) throw () ; # 800 "/usr/include/stdio.h" 3 4 extern FILE *popen (const char *__command, const char *__modes) ;      extern int pclose (FILE *__stream);      extern char *ctermid (char *__s) throw ();      extern char *cuserid (char *__s);     struct obstack;   extern int obstack_printf (struct obstack *__restrict __obstack,       const char *__restrict __format, ...)      throw () __attribute__ ((__format__ (__printf__, 2, 3))); extern int obstack_vprintf (struct obstack *__restrict __obstack,        const char *__restrict __format,        __gnuc_va_list __args)      throw () __attribute__ ((__format__ (__printf__, 2, 0)));        extern void flockfile (FILE *__stream) throw ();    extern int ftrylockfile (FILE *__stream) throw () ;   extern void funlockfile (FILE *__stream) throw (); # 868 "/usr/include/stdio.h" 3 4 } # 1 "<stdin>" 2
extern FILE *fmemopen (void *__s, size_t __len, const char *__modes)
1
1
Makefile:60: *** invalid syntax in conditional.  Stop.
```

**Comment by glx22** [comment] 2021-03-10 17:56
Should be fixed now with the CMake switch.

**Closed by glx22** 2021-03-10 17:56 UTC
